import{a as f}from"./assets/vendor-34f890c2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const v=document.querySelector(".but"),p=document.querySelector(".mdl_box"),u=document.querySelector(".mdl_forma"),L=document.querySelector(".close"),a=document.querySelector(".username"),S=document.querySelector(".but_submit"),r=document.querySelector(".phone"),k=document.querySelector(".forma_for_connect"),g="6077606622:AAG6g12itzLvnsQfazmk9-oBfkHb1kflQYk";let h;f.get(`https://api.telegram.org/bot${g}/getUpdates`).then(t=>{h=t.data.result[t.data.result.length-1].message.chat.id}).catch(t=>console.log(t.massage));async function d(){a.value.trim()===""?a.classList.add("red"):a.classList.remove("red")}async function m(){r.value.trim()===""||!r.value.trim().includes("+")||r.value.trim().split("").length<12?r.classList.add("red"):r.classList.remove("red")}async function q(){u.innerHTML="",u.style.height="312px";let t="";t+=`<svg class="close" fill="black" width="14" height="14">
                    <use href="./sprite.svg#icon-close"></use>
                </svg>
                <h2 class="title_feedback">See you soon!</h2>
                <p class="text_feedback">Ваші дані були успішно відправлені. 
                Будь ласка, очікуйте: я зв'яжуся з Вами якнайшвидше для обговорення деталей.</p>`,u.innerHTML=t;const o=document.querySelector(".title_feedback");o.style.fontSize="80px",o.style.margin="0",o.style.textAlign="center"}v.addEventListener("click",t=>{p.style.display="flex"});L.addEventListener("click",t=>{p.style.display="none"});a.addEventListener("input",t=>{d()});r.addEventListener("input",t=>{m()});S.addEventListener("click",t=>{d(),m()});k.addEventListener("submit",async t=>{t.preventDefault(),d(),m();async function o(b){await f.post(`https://api.telegram.org/bot${g}/sendMessage`,{chat_id:h,text:b}).then(l=>{q(),l.status}).catch(l=>{l(),console.error("Error in sending sms:",l)})}const n=new FormData(document.querySelector(".forma_for_connect")),i=n.get("username"),e=n.get("phone"),s=n.get("education"),c=n.get("comment"),y=`
            Нова заявка:
    1) Им'я: ${i};
    2) Телефон: ${e};
    3) Формат навчання: ${s};
    4) Коментар: ${c.split("").length>0?c:"Without comments"};
        `;o(y)});
//# sourceMappingURL=commonHelpers.js.map
