import{a as m}from"./assets/vendor-34f890c2.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const L=document.querySelector(".but"),f=document.querySelector(".mdl_box"),p=document.querySelector(".mdl_content"),S=document.querySelector(".close"),l=document.querySelector(".username"),v=document.querySelector(".but_submit"),c=document.querySelector(".phone"),k=document.querySelector(".forma_for_connect");document.querySelector("label-inpt");const y="6077606622:AAG6g12itzLvnsQfazmk9-oBfkHb1kflQYk";let g;m.get(`https://api.telegram.org/bot${y}/getUpdates`).then(t=>{g=t.data.result[t.data.result.length-1].message.chat.id}).catch(t=>console.log(t.massage));async function u(){l.value.trim()===""?l.classList.add("red"):l.classList.remove("red")}async function d(){c.value.trim()===""||!c.value.trim().includes("+")||c.value.trim().split("").length<12?c.classList.add("red"):c.classList.remove("red")}async function _(){let t=`
                <h2 class="title_feedback">See you soon!</h2>
                <p class="text_feedback">Ваші дані були успішно відправлені.
                Будь ласка, очікуйте: я зв'яжуся з Вами якнайшвидше для обговорення деталей.</p>`;p.innerHTML=t;const n=document.querySelector(".title_feedback");n.style.fontSize="80px",n.style.margin="0",n.style.textAlign="center"}async function q(){let t=`
                <h2 class="title_feedback">Error</h2>
                <p class="text_feedback">На жаль, на сайті сталася помилка і Ваші дані не були відправлені. Спробуйте, будь ласка, пізніше.</p>`;p.innerHTML=t;const n=document.querySelector(".title_feedback");n.style.fontSize="80px",n.style.margin="0",n.style.textAlign="center"}L.addEventListener("click",function(){f.style.display="block"});S.addEventListener("click",function(){f.style.display="none"});l.addEventListener("input",t=>{u()});c.addEventListener("input",t=>{d()});v.addEventListener("click",t=>{u(),d()});k.addEventListener("submit",async t=>{t.preventDefault(),u(),d();async function n(b){await m.post(`https://api.telegram.org/bot${y}/sendMessage`,{chat_id:g,text:b}).then(a=>{_(),a.status}).catch(a=>{q(),console.error("Error in sending sms:",a)})}const s=new FormData(document.querySelector(".forma_for_connect")),i=s.get("username"),e=s.get("phone"),o=s.get("education"),r=s.get("comment"),h=`
            Нова заявка:
    1) Им'я: ${i};
    2) Телефон: ${e};
    3) Формат навчання: ${o};
    4) Коментар: ${r.split("").length>0?r:"Without comments"};
        `;n(h)});
//# sourceMappingURL=commonHelpers.js.map
